/* global api, loaders, user */
// Owned-content playlists: separate from paid advertising campaigns.
const playlistState={playlist:null,menus:[],media:[],screens:[],delivery:[]};
const plEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const plAdmin=()=>['admin','superadmin'].includes(user?.role);
const plLocation=s=>typeof s?.location==='object'?[s.location.city,s.location.state].filter(Boolean).join(', '):(s?.location||s?.status||'Screen');

(function addPlaylistStyles(){
  if(document.getElementById('playlist-styles'))return;
  const style=document.createElement('style');style.id='playlist-styles';style.textContent=`
  .pl-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:16px}.pl-card{background:var(--bg-card);border:1px solid var(--border);border-radius:16px;padding:18px;cursor:pointer;transition:.2s}.pl-card:hover{border-color:var(--brand);transform:translateY(-2px)}
  .pl-pill{display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border-radius:99px;background:var(--ds-neutral-soft);color:var(--t-3);font-size:11px;font-weight:800}.pl-pill.live{background:var(--ds-success-soft);color:var(--ds-success)}.pl-editor{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(280px,.8fr);gap:18px}.pl-item{display:grid;grid-template-columns:42px minmax(0,1fr) 92px 112px 110px;gap:10px;align-items:center;padding:12px;border:1px solid var(--border);border-radius:12px;background:var(--ds-surface-2);margin-bottom:8px}.pl-modal{position:fixed;inset:0;background:rgba(15,23,42,.55);z-index:250;display:flex;align-items:center;justify-content:center;padding:18px;backdrop-filter:blur(8px)}.pl-modal-box{width:min(720px,100%);max-height:90vh;overflow:auto;background:var(--bg-card);border:1px solid var(--border);border-radius:18px;padding:22px;box-shadow:var(--ds-sh-xl)}
  .pl-screen{display:flex;align-items:center;gap:12px;padding:12px;border:1px solid var(--border);border-radius:12px;margin-top:8px}.pl-screen input{width:18px;height:18px}.pl-empty{padding:42px 18px;text-align:center;border:1px dashed var(--border);border-radius:16px;color:var(--t-4)}
  .pl-add-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.pl-day-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:6px}.pl-day{display:flex;flex-direction:column;align-items:center;gap:4px;padding:8px 2px;border:1px solid var(--border);border-radius:8px;font-size:11px;color:var(--t-3)}
  .pl-modal-box textarea.inp{resize:vertical}.pl-modal-box input[type="checkbox"]{accent-color:var(--brand)}
  @media(max-width:820px){.pl-editor{grid-template-columns:1fr}.pl-item{grid-template-columns:36px minmax(0,1fr);}.pl-item .pl-duration,.pl-item .pl-display-mode,.pl-item .pl-actions{grid-column:2}.pl-add-grid{grid-template-columns:1fr}.pl-day-grid{grid-template-columns:repeat(4,1fr)}}
  `;document.head.appendChild(style);
})();

function playlistModal(title,body){
  document.getElementById('playlist-modal')?.remove();
  const modal=document.createElement('div');modal.id='playlist-modal';modal.className='pl-modal';modal.innerHTML=`<div class="pl-modal-box" data-testid="playlist-modal"><div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:18px"><div><div style="font-size:11px;color:#22d3ee;font-weight:900;letter-spacing:.12em">OWNED CONTENT</div><h2 style="font-size:21px;margin-top:5px">${plEsc(title)}</h2></div><button class="btn-icon" data-testid="playlist-modal-close" onclick="closePlaylistModal()">×</button></div>${body}</div>`;document.body.appendChild(modal);
}
function closePlaylistModal(){document.getElementById('playlist-modal')?.remove()}
function playlistStatus(text,ok=true){const n=document.getElementById('playlist-modal-status');if(n){n.style.color=ok?'#34d399':'#f87171';n.textContent=text}}

loaders.playlists=async function(){
  const el=document.getElementById('pg-playlists');el.innerHTML='<div class="sk h80"></div><div class="sk h80"></div>';
  try{
    const playlists=await api('/playlists');
    el.innerHTML=`<div class="ph"><div><div class="ey">CONTENT OPERATIONS</div><h1>Playlists</h1><p>Permanent content owned by each business, separate from paid campaigns.</p></div><button class="btn-p" data-testid="playlist-create-button" onclick="newPlaylist()">+ New Playlist</button></div>
    ${playlists.length?`<div class="pl-grid">${playlists.map(p=>`<article class="pl-card" data-testid="playlist-card-${p.id}" onclick="openPlaylist('${p.id}')"><div style="display:flex;justify-content:space-between;gap:10px"><div class="pl-pill ${p.status==='published'?'live':''}">${p.status==='published'?'Published':'Draft'}</div><div class="pl-pill">${plEsc(p.management_mode||'admin')} managed</div></div><h3 style="font-size:18px;margin:15px 0 6px">${plEsc(p.name)}</h3><p style="color:var(--t-4);font-size:12px;min-height:34px">${plEsc(p.description||'No description')}</p><div style="display:flex;gap:16px;margin-top:16px;font-size:12px;color:var(--t-3)"><span>${(p.items||[]).length} items</span><span>${(p.screen_ids||[]).length} screens</span><span>v${p.version||1}</span></div></article>`).join('')}</div>`:`<div class="pl-empty" data-testid="playlist-empty-state"><h3 style="color:var(--t-2);margin-bottom:8px">No playlists yet</h3><p>Create a playlist for a restaurant, store, office, or public screen.</p><button class="btn-p" data-testid="playlist-create-first-button" style="margin-top:18px" onclick="newPlaylist()">Create first playlist</button></div>`}`;
  }catch(e){el.innerHTML=`<div class="empty"><h3>Unable to load playlists</h3><p>${plEsc(e.message)}</p></div>`}
};

async function newPlaylist(){
  const adminFields=plAdmin()?`<label class="inp-label" style="margin-top:12px">Management mode</label><select id="pl-new-mode" data-testid="playlist-mode-select" class="inp"><option value="admin">Managed by our team</option><option value="client">Client self-service</option><option value="public">Public link / QR</option></select><label class="inp-label" style="margin-top:12px">Client account</label><select id="pl-new-client" data-testid="playlist-client-select" class="inp"><option value="">Loading client accounts…</option></select><label style="display:flex;gap:9px;align-items:center;margin-top:14px;color:var(--t-2);font-size:13px"><input id="pl-new-direct" data-testid="playlist-direct-publish-toggle" type="checkbox"> Allow this client to publish directly</label>`:'';
  playlistModal('Create playlist',`<label class="inp-label">Playlist name</label><input id="pl-new-name" data-testid="playlist-name-input" class="inp" placeholder="Tony's Pizzeria · Main Menu"><label class="inp-label" style="margin-top:12px">Description</label><textarea id="pl-new-description" data-testid="playlist-description-input" class="inp" rows="2" placeholder="Breakfast, lunch, promotions…"></textarea>${adminFields}<div id="playlist-modal-status" data-testid="playlist-modal-status" style="margin-top:12px;font-size:13px"></div><div style="display:flex;justify-content:flex-end;gap:10px;margin-top:20px"><button class="btn-s" data-testid="playlist-create-cancel" onclick="closePlaylistModal()">Cancel</button><button class="btn-p" data-testid="playlist-create-confirm" onclick="createPlaylist()">Create playlist</button></div>`);
  if(plAdmin()){try{const result=await api('/admin/users');const clients=Array.isArray(result)?result:(result.users||[]);const select=document.getElementById('pl-new-client');if(select)select.innerHTML='<option value="">No client assigned</option>'+clients.map(c=>`<option value="${c.id}">${plEsc(c.company_name||c.name||c.email)}</option>`).join('')}catch(_){const select=document.getElementById('pl-new-client');if(select)select.innerHTML='<option value="">Client list unavailable</option>'}}
}
async function createPlaylist(){
  try{const body={name:document.getElementById('pl-new-name').value,description:document.getElementById('pl-new-description').value};if(plAdmin()){body.management_mode=document.getElementById('pl-new-mode').value;body.client_user_id=document.getElementById('pl-new-client').value||null;body.allow_client_publish=document.getElementById('pl-new-direct').checked}const created=await api('/playlists',{method:'POST',body:JSON.stringify(body)});closePlaylistModal();openPlaylist(created.id)}catch(e){playlistStatus(e.message,false)}
}

async function openPlaylist(id){
  activatePlaylistPage();const el=document.getElementById('pg-playlists');el.innerHTML='<div class="sk h80"></div><div class="sk h80"></div>';
  try{
    const [playlist,menus,media,screens,delivery]=await Promise.all([api('/playlists/'+id),api('/menus'),api('/media'),api('/playlists/'+id+'/available-screens'),api('/playlists/'+id+'/delivery-status')]);
    playlistState.playlist=playlist;playlistState.menus=menus||[];playlistState.media=media||[];playlistState.screens=screens||[];playlistState.delivery=delivery||[];renderPlaylistEditor();
  }catch(e){el.innerHTML=`<div class="empty" data-testid="playlist-open-error"><h3>Unable to open playlist</h3><p>${plEsc(e.message)}</p><button class="btn-s" data-testid="playlist-open-error-back" onclick="loaders.playlists()">Back</button></div>`}
}
function activatePlaylistPage(){document.querySelectorAll('.pg').forEach(x=>x.classList.remove('on'));document.getElementById('pg-playlists').classList.add('on');document.querySelectorAll('.ni').forEach(n=>n.classList.remove('on'));document.querySelector('[data-p="playlists"]')?.classList.add('on')}

function renderPlaylistEditor(){
  const p=playlistState.playlist,el=document.getElementById('pg-playlists'),items=p.items||[];
  const pending=p.pending_items||[];
  el.innerHTML=`<div class="ph"><div><button class="btn-s" data-testid="playlist-back-button" onclick="loaders.playlists()" style="margin-bottom:12px">← All playlists</button><div class="ey">${plEsc(p.management_mode||'admin')} managed · version ${p.version||1}</div><h1>${plEsc(p.name)}</h1><p>${plEsc(p.description||'Owned content playlist')}</p></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn-s" data-testid="playlist-edit-details" onclick="openPlaylistDetails()">Edit details</button><button class="btn-s" data-testid="playlist-share-button" onclick="openPlaylistShare()">Public link / QR</button>${p.status==='published'?'<button class="btn-s" data-testid="playlist-unpublish-button" onclick="unpublishPlaylist()">Unpublish</button>':''}<button class="btn-p" data-testid="playlist-publish-button" onclick="openPlaylistPublish()">${p.status==='published'?'Update screens':'Publish to screens'}</button></div></div>
  <div class="pl-editor"><section><div class="card" style="padding:18px"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:14px"><div><h2 style="font-size:17px">Playlist timeline</h2><p style="color:var(--t-4);font-size:12px;margin-top:4px">Menus, images and videos play from top to bottom.</p><div id="playlist-editor-status" data-testid="playlist-editor-status" class="meta" style="margin-top:5px"></div></div><button class="btn-s" data-testid="playlist-save-button" onclick="savePlaylist()">Save changes</button></div>
  <div id="playlist-items">${items.length?items.map((item,index)=>playlistItemHtml(item,index)).join(''):'<div class="pl-empty">Add a menu, image, or video to begin.</div>'}</div>
  <div style="display:flex;justify-content:flex-end;margin-top:14px"><button class="btn-s" data-testid="playlist-refresh-sources-button" onclick="refreshPlaylistSources()">Refresh menus & media</button></div><div class="pl-add-grid"><div><label class="inp-label">Add menu</label><select id="pl-add-menu" data-testid="playlist-add-menu-select" class="inp"><option value="">Select menu…</option>${playlistState.menus.map(m=>`<option value="${m.id}">${plEsc(m.name)}</option>`).join('')}</select><button class="btn-s" data-testid="playlist-add-menu-button" style="width:100%;margin-top:8px" onclick="addPlaylistItem('menu')">Add menu</button></div><div><label class="inp-label">Add image or video</label><select id="pl-add-media" data-testid="playlist-add-media-select" class="inp"><option value="">Select media…</option>${playlistState.media.map(m=>`<option value="${m.id}">${plEsc(m.filename)}</option>`).join('')}</select><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px"><button class="btn-s" data-testid="playlist-add-media-button" onclick="addPlaylistItem('media')">Add library item</button><button class="btn-s" data-testid="playlist-upload-media-button" onclick="document.getElementById('pl-upload-file').click()">Upload new</button></div><input id="pl-upload-file" data-testid="playlist-upload-file-input" type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4" hidden onchange="uploadPlaylistMedia(this)"><div id="pl-upload-status" data-testid="playlist-upload-status" class="meta" style="margin-top:7px"></div></div></div></div>
  ${pending.length?`<div class="card" data-testid="playlist-pending-submissions" style="padding:18px;margin-top:16px"><h2 style="font-size:17px">Pending public submissions</h2>${pending.map(item=>`<div class="pl-item" data-testid="playlist-pending-item-${item.id}"><div class="pl-pill">NEW</div><div><strong>${plEsc(item.title)}</strong><div class="meta">Waiting for approval</div></div><div class="pl-actions" style="display:flex;gap:6px"><button class="btn-s" data-testid="playlist-pending-approve-${item.id}" onclick="reviewPlaylistSubmission('${item.id}',true)">Approve</button><button class="btn-s" data-testid="playlist-pending-reject-${item.id}" onclick="reviewPlaylistSubmission('${item.id}',false)">Reject</button></div></div>`).join('')}</div>`:''}</section>
  <aside><div class="card" data-testid="playlist-delivery-status" style="padding:18px"><h2 style="font-size:17px">Delivery</h2><div style="margin-top:12px"><div class="pl-pill ${p.status==='published'?'live':''}">${p.status==='published'?'Published':'Draft'}</div></div>${playlistState.delivery.length?playlistState.delivery.map(s=>`<div class="pl-screen" data-testid="playlist-delivery-screen-${s.id}"><span style="width:9px;height:9px;border-radius:50%;background:${s.device_status==='online'?'#34d399':'#64748b'}"></span><div><strong style="font-size:13px">${plEsc(s.name)}</strong><div class="meta">${plEsc(s.device_status)}${s.last_seen?' · '+plEsc(new Date(s.last_seen).toLocaleString()):''}</div></div></div>`).join(''):'<p style="color:var(--t-4);font-size:12px;margin-top:14px">Not assigned to a screen yet.</p>'}</div>
  <div class="card" style="padding:18px;margin-top:16px"><h2 style="font-size:17px">Control</h2><p class="meta" style="margin-top:8px">${p.management_mode==='client'?'Client can manage content'+(p.allow_client_publish?' and publish directly.':'; administrator publishes.') : p.management_mode==='public'?'Secured public link or QR controls this playlist.':'Managed by your operations team.'}</p></div></aside></div>`;
}

function playlistItemHtml(item,index){const mode=item.display_mode||'cover';return `<div class="pl-item" data-testid="playlist-item-${item.id}"><div class="pl-pill">${index+1}</div><div><strong>${plEsc(item.title)}</strong><div class="meta">${plEsc(item.type)} · ${plEsc(item.transition||'fade')}</div></div><div class="pl-duration"><input data-testid="playlist-item-duration-${item.id}" class="inp" type="number" min="3" value="${item.duration||15}" onchange="playlistState.playlist.items[${index}].duration=Number(this.value)" title="Seconds"></div><div class="pl-display-mode"><select data-testid="playlist-item-display-${item.id}" class="inp" onchange="playlistState.playlist.items[${index}].display_mode=this.value"><option value="cover" ${mode==='cover'?'selected':''}>Cover</option><option value="contain" ${mode==='contain'?'selected':''}>Contain</option><option value="stretch" ${mode==='stretch'?'selected':''}>Stretch</option></select></div><div class="pl-actions" style="display:flex;gap:4px"><button data-testid="playlist-item-up-${item.id}" class="btn-icon" onclick="movePlaylistItem(${index},-1)" title="Move up">↑</button><button data-testid="playlist-item-down-${item.id}" class="btn-icon" onclick="movePlaylistItem(${index},1)" title="Move down">↓</button><button data-testid="playlist-item-remove-${item.id}" class="btn-icon" onclick="removePlaylistItem(${index})" title="Remove" style="color:#f87171">×</button></div></div>`}
function addPlaylistItem(type){const select=document.getElementById(type==='menu'?'pl-add-menu':'pl-add-media');if(!select.value)return;const option=select.options[select.selectedIndex];playlistState.playlist.items=playlistState.playlist.items||[];playlistState.playlist.items.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),type,ref_id:select.value,title:option.text,duration:type==='menu'?60:15,transition:'fade',display_mode:'cover',order:playlistState.playlist.items.length});renderPlaylistEditor()}
function movePlaylistItem(index,delta){const items=playlistState.playlist.items,target=index+delta;if(target<0||target>=items.length)return;[items[index],items[target]]=[items[target],items[index]];renderPlaylistEditor()}
function removePlaylistItem(index){playlistState.playlist.items.splice(index,1);renderPlaylistEditor()}
async function refreshPlaylistSources(showStatus=true){try{const [menus,media,screens]=await Promise.all([api('/menus'),api('/media'),api('/screens')]);playlistState.menus=menus;playlistState.media=media;playlistState.screens=screens;renderPlaylistEditor();if(showStatus){const status=document.getElementById('playlist-editor-status');if(status){status.style.color='var(--ds-success)';status.textContent='Menus and media refreshed.'}}}catch(e){const status=document.getElementById('playlist-editor-status');if(status){status.style.color='var(--red)';status.textContent=e.message}}}
async function savePlaylist(){try{playlistState.playlist=await api('/playlists/'+playlistState.playlist.id,{method:'PUT',body:JSON.stringify({items:playlistState.playlist.items})});renderPlaylistEditor();const status=document.getElementById('playlist-editor-status');if(status){status.style.color='var(--ds-success)';status.textContent='Changes saved and queued for screen sync.'}}catch(e){const status=document.getElementById('playlist-editor-status');if(status){status.style.color='var(--red)';status.textContent=e.message}else alert(e.message)}}
function openPlaylistDetails(){const p=playlistState.playlist;playlistModal('Edit playlist details',`<label class="inp-label">Name</label><input id="pl-edit-name" data-testid="playlist-edit-name-input" class="inp" value="${plEsc(p.name)}"><label class="inp-label" style="margin-top:12px">Description</label><textarea id="pl-edit-description" data-testid="playlist-edit-description-input" class="inp" rows="3">${plEsc(p.description||'')}</textarea><div id="playlist-modal-status" data-testid="playlist-details-status" style="margin-top:12px"></div><button class="btn-p" data-testid="playlist-details-save" style="width:100%;margin-top:18px" onclick="savePlaylistDetails()">Save details</button>`)}
async function savePlaylistDetails(){try{playlistState.playlist=await api('/playlists/'+playlistState.playlist.id,{method:'PUT',body:JSON.stringify({name:document.getElementById('pl-edit-name').value,description:document.getElementById('pl-edit-description').value})});closePlaylistModal();renderPlaylistEditor()}catch(e){playlistStatus(e.message,false)}}
async function uploadPlaylistMedia(input){const file=input.files?.[0];if(!file)return;const status=document.getElementById('pl-upload-status');if(file.size>100*1024*1024){status.textContent='File exceeds 100 MB.';status.style.color='#f87171';return}status.textContent='Uploading '+file.name+'…';status.style.color='#22d3ee';const reader=new FileReader();reader.onerror=()=>{status.textContent='Unable to read this file.';status.style.color='#f87171'};reader.onload=async()=>{try{const uploaded=await api('/media/upload',{method:'POST',body:JSON.stringify({filename:file.name,content_type:file.type||'application/octet-stream',data:String(reader.result).split(',')[1]})});playlistState.media.push(uploaded);playlistState.playlist.items.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),type:'media',ref_id:uploaded.id,title:uploaded.filename,duration:(uploaded.content_type||'').startsWith('video/')?30:15,transition:'fade',display_mode:'cover',order:playlistState.playlist.items.length});await savePlaylist()}catch(e){status.textContent=e.message;status.style.color='#f87171'}finally{input.value=''}};reader.readAsDataURL(file)}

async function openPlaylistPublish(){
  const p=playlistState.playlist;if(!playlistState.screens.length){alert('No screens are available for this playlist. Assign screens to the client first.');return}
  const schedule=p.schedule||{},scheduled=schedule.mode==='scheduled',days=schedule.days||[0,1,2,3,4,5,6],labels=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
  playlistModal('Publish to screens',`<p style="color:var(--t-3);font-size:13px">Choose one or many screens. The highest-priority active playlist wins automatically.</p><div style="margin-top:14px;max-height:300px;overflow:auto">${playlistState.screens.map(s=>`<label class="pl-screen"><input data-testid="playlist-screen-${s.id}" class="pl-publish-screen" type="checkbox" value="${s.id}" ${(p.screen_ids||[]).includes(s.id)?'checked':''}><div><strong>${plEsc(s.name)}</strong><div class="meta">${plEsc(plLocation(s))}</div></div></label>`).join('')}</div><label class="inp-label" style="margin-top:16px">Schedule</label><select id="pl-schedule-mode" data-testid="playlist-schedule-mode" class="inp" onchange="document.getElementById('pl-schedule-fields').style.display=this.value==='scheduled'?'block':'none'"><option value="always" ${scheduled?'':'selected'}>Always active</option><option value="scheduled" ${scheduled?'selected':''}>Scheduled override</option></select><div id="pl-schedule-fields" style="display:${scheduled?'block':'none'};margin-top:10px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div><label class="inp-label">Start time</label><input id="pl-start-time" data-testid="playlist-start-time" type="time" class="inp" value="${plEsc(schedule.start_time||'08:00')}"></div><div><label class="inp-label">End time</label><input id="pl-end-time" data-testid="playlist-end-time" type="time" class="inp" value="${plEsc(schedule.end_time||'22:00')}"></div><div><label class="inp-label">Start date (optional)</label><input id="pl-start-date" data-testid="playlist-start-date" type="date" class="inp" value="${plEsc(schedule.start_date||'')}"></div><div><label class="inp-label">End date (optional)</label><input id="pl-end-date" data-testid="playlist-end-date" type="date" class="inp" value="${plEsc(schedule.end_date||'')}"></div></div><label class="inp-label" style="margin-top:12px">Active days</label><div class="pl-day-grid">${labels.map((label,day)=>`<label class="pl-day"><input class="pl-schedule-day" data-testid="playlist-day-${day}" type="checkbox" value="${day}" ${days.includes(day)?'checked':''}>${label}</label>`).join('')}</div></div><label class="inp-label" style="margin-top:12px">Priority</label><input id="pl-priority" data-testid="playlist-priority" class="inp" type="number" min="0" max="100" value="${p.priority||10}"><div id="playlist-modal-status" data-testid="playlist-publish-status" style="margin-top:12px;font-size:13px"></div><div style="display:flex;justify-content:flex-end;gap:10px;margin-top:18px"><button class="btn-s" data-testid="playlist-publish-cancel" onclick="closePlaylistModal()">Cancel</button><button class="btn-p" data-testid="playlist-publish-confirm" onclick="publishPlaylist()">Confirm publish</button></div>`);
}
async function publishPlaylist(){try{const screen_ids=[...document.querySelectorAll('.pl-publish-screen:checked')].map(x=>x.value);const mode=document.getElementById('pl-schedule-mode').value;const days=[...document.querySelectorAll('.pl-schedule-day:checked')].map(x=>Number(x.value));if(mode==='scheduled'&&!days.length)throw new Error('Select at least one active day.');const start_date=document.getElementById('pl-start-date')?.value||null,end_date=document.getElementById('pl-end-date')?.value||null;if(start_date&&end_date&&start_date>end_date)throw new Error('End date must be on or after start date.');const schedule={mode,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'America/New_York',start_time:document.getElementById('pl-start-time')?.value||'00:00',end_time:document.getElementById('pl-end-time')?.value||'23:59',start_date,end_date,days:mode==='scheduled'?days:[0,1,2,3,4,5,6]};const result=await api('/playlists/'+playlistState.playlist.id+'/publish',{method:'POST',body:JSON.stringify({screen_ids,schedule,priority:Number(document.getElementById('pl-priority').value)})});playlistStatus('Published to '+result.screen_ids.length+' screen(s).');setTimeout(()=>{closePlaylistModal();openPlaylist(playlistState.playlist.id)},800)}catch(e){playlistStatus(e.message,false)}}
async function unpublishPlaylist(){if(!confirm('Remove this playlist from all screens?'))return;try{await api('/playlists/'+playlistState.playlist.id+'/unpublish',{method:'POST'});openPlaylist(playlistState.playlist.id)}catch(e){alert(e.message)}}

function openPlaylistShare(){playlistModal('Public link / QR',`<p style="color:var(--t-3);font-size:13px">Create a secure link for staff, franchisees, or the public. Rotate it any time.</p><label class="inp-label" style="margin-top:14px">Permission</label><select id="pl-share-permission" data-testid="playlist-share-permission" class="inp"><option value="editor">Upload and remove content</option><option value="uploader">Upload only</option></select><label style="display:flex;gap:9px;align-items:center;margin-top:14px;color:var(--t-2);font-size:13px"><input id="pl-share-approval" data-testid="playlist-share-approval" type="checkbox" checked> Require approval before content appears</label><label class="inp-label" style="margin-top:14px">Expires after</label><select id="pl-share-days" data-testid="playlist-share-expiry" class="inp"><option value="7">7 days</option><option value="30" selected>30 days</option><option value="90">90 days</option><option value="365">1 year</option></select><div id="playlist-modal-status" data-testid="playlist-share-status" style="margin-top:12px;font-size:13px"></div><button class="btn-p" style="width:100%;margin-top:18px" data-testid="playlist-share-generate" onclick="generatePlaylistShare()">Generate secure link</button><div id="pl-share-result" data-testid="playlist-share-result"></div>`)}
async function generatePlaylistShare(){try{const result=await api('/playlists/'+playlistState.playlist.id+'/share',{method:'POST',body:JSON.stringify({permission:document.getElementById('pl-share-permission').value,require_approval:document.getElementById('pl-share-approval').checked,expires_days:Number(document.getElementById('pl-share-days').value),allow_upload:true})});document.getElementById('pl-share-result').innerHTML=`<div class="card" data-testid="playlist-share-generated" style="padding:14px;margin-top:16px;text-align:center"><img data-testid="playlist-share-qr" src="${result.qr_url}" alt="Playlist QR" style="width:190px;height:190px;background:white;padding:8px;border-radius:12px"><input id="pl-share-url" data-testid="playlist-share-url" class="inp" value="${plEsc(result.url)}" readonly style="margin-top:12px"><button class="btn-s" data-testid="playlist-share-copy" style="width:100%;margin-top:8px" onclick="navigator.clipboard.writeText(document.getElementById('pl-share-url').value)">Copy secure URL</button></div>`}catch(e){playlistStatus(e.message,false)}}
async function reviewPlaylistSubmission(itemId,approve){try{const path='/playlists/'+playlistState.playlist.id+'/pending/'+itemId+(approve?'/approve':'');await api(path,{method:approve?'POST':'DELETE'});openPlaylist(playlistState.playlist.id)}catch(e){alert(e.message)}}

window.openMenuPlaylistPublish=async function(menuId){try{const playlist=await api('/menus/'+menuId+'/prepare-playlist',{method:'POST'});await openPlaylist(playlist.id);openPlaylistPublish()}catch(e){alert(e.message)}};
window.addEventListener('mediaview:sources-changed',()=>{if(playlistState.playlist)refreshPlaylistSources(false)});